const BASIC_MATERIALS_DB = {
    "小麦": { category: "農作物", level: 1, time: 2, cost: 0 },
    "トウモロコシ": { category: "農作物", level: 3, time: 5, cost: 1 },
    "にんじん": { category: "農作物", level: 4, time: 10, cost: 2 },
    "サトウキビ": { category: "農作物", level: 7, time: 20, cost: 3 },
    "綿": { category: "農作物", level: 9, time: 30, cost: 4 },
    "イチゴ": { category: "農作物", level: 13, time: 60, cost: 5 },
    "トマト": { category: "農作物", level: 15, time: 120, cost: 6 },
    "松の木": { category: "農作物", level: 18, time: 180, cost: 7 },
    "ジャガイモ": { category: "農作物", level: 22, time: 240, cost: 8 },
    "カカオ": { category: "農作物", level: 25, time: 480, cost: 9 },
    "ゴムの木": { category: "農作物", level: 29, time: 720, cost: 15 },
    "絹": { category: "農作物", level: 31, time: 900, cost: 20 },
    "コルクガシ": { category: "農作物", level: 37, time: 600, cost: 12 },
    "唐辛子": { category: "農作物", level: 43, time: 300, cost: 11 },
    "ミント": { category: "農作物", level: 50, time: 165, cost: 21 },
    "米": { category: "農作物", level: 56, time: 80, cost: 7 },
    "バラ": { category: "農作物", level: 61, time: 150, cost: 18 },
    "ジャスミン": { category: "農作物", level: 67, time: 210, cost: 25 },
    "コーヒーの木": { category: "農作物", level: 72, time: 360, cost: 33 },
    "ピーナッツ": { category: "農作物", level: 75, time: 420, cost: 35 },
    "リンゴ": { category: "農作物", level: 80, time: 450, cost: 36 },
    "茶の苗": { category: "農作物", level: 84, time: 540, cost: 37 },
    "大豆": { category: "農作物", level: 90, time: 120, cost: 8 },
    "ラベンダー": { category: "農作物", level: 94, time: 300, cost: 27 }
};